### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 824

### ISSUE THREAD

**Issue by anhtuan23** [matthin/cedict_to_sqlite#1]
Hi, I tried to run your program but got the following error: 

`Traceback (most recent call last):
  File "cedict_to_sqlite.py", line 17, in <module>
    for line in f:
  File "C:\Users\dotua\.virtualenvs\cedict_to_sqlite-84VUtQTv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 824: character maps to <undefined>`

I am using Windows 10, python 3.6.5. Can you help?

**Comment by anhtuan23** [comment]
Well I edit the code as you said and it's WORKED! Thanks a a lot for your help and your program. I was thinking I would have to rewrite the converter in Java so your work saved me a lot of troubles 👍

**Comment by matthin** [comment]
Thanks for helping me getting the program working on windows.

Also just to let you know, this program modifies the pinyin values right [here](https://github.com/matthin/cedict_to_sqlite/blob/master/cedict_to_sqlite.py#L21). Just in case you notice those values being weird.

I made this program specificially for https://github.com/matthin/anki_chinese_helper, and wanted the pinyin values to have the character accents instead of the numbers, but I actually think I may move that logic into my anki_chinese_helper program instead.

So later I'll be pushing that windows fix, and then maybe removing that one line of code to keep the pinyin values as they originally are in the cedict.txt.gz file. If though you want those pinyin changes to be left as is, I can make that a command line option if you want.

**Comment by anhtuan23** [comment]
Indeed having the tones as number help you do cool tricks like coloring hanzi accordingly, and since converting  from number to tone mark is always easier, it should be preserved. In this case I would like to have an option to create both pinyin with number and pinyin with tone mark columns, if you would be so kind.

I am developing an Android app with word segmentation to help reading Chinese easier and the Cedict database is also used for Anki integration :)

**Comment by matthin** [comment]
The colouring is the exact reason why I wanted to move those changes out, so that's good. Just to be clear, do you want that option to create two columns in the database, one for the pinyin with numbers and one for pinyin with accent marks? Or an option to just create one of either of the columns? I'm guessing the former but I just want to make sure.

Also later I'm planning on adding a library interface to the program, so I can more easily integrate this project with my other python anki program. I'll still be leaving the command line stuff as is though, so everything will still work fine with your android app.

**Comment by anhtuan23** [comment]
You are right, I would like the former. Thanks again for your help. Have fun with your project.

**Comment by matthin** [comment]
1b244c4 and d6b8b55 solves both issues.
