### ISSUE TITLE
Bugs in SQL commands and pinyin conversion

### ISSUE THREAD

**Issue by anhtuan23** [matthin/cedict_to_sqlite#2]
Hi, there is a small bug in your program. In line `88` of `cedict_to_sqlite.py` there should be only 4 placeholders instead of 5.

Also the pinyin converter has not accounted for `er hua` with tone number. So pinyin for words like `那儿` produces `nà r5` instead of `nàr`.

Sorry I couldn't help you since I am really not familiar with python.

**Comment by matthin** [comment]
Thanks for telling me about the bugs.

For the placeholder bug, did that cause an sql error on your system, or did you just notice in when looking at the code? Because that doesn't cause an error on my system which really seems odd.

And really thanks a lot for telling me about the 2nd bug. Back when I first developed the project I was kinda lazy so I just copied pinyin.py from the stackoverflow link I commented at the top of the file. I'm not really the best with python either, and the code is pretty unreadable so I'll probably completely rewrite that section.

**Comment by matthin** [comment]
Well this is kind of dumb of me. I was passing `--enable-tone-accents false`, but that doesn't falsify the boolean, instead just that argument existing with or without any value flips the boolean to true. So I just didn't even test my changes properly since it was always hitting the true branch.

I really can barely understand anything at all from that code either lol.

For erhua, does the r simply get added without any conjugation in every case? From what I read it seems so, but I don't know any Chinese so I just want to make sure I'm not introducing another bug.

**Comment by anhtuan23** [comment]
Yes, every `r5` is just an extension of the previous syllable. As to whether it should be appended to that syllable without any space, there is no standard. But I think keeping the space is preferable. So you just have to remove `5` from `r5`.

Are you learning Chinese or are you developing these projects for other objectives?

**Comment by anhtuan23** [comment]
Well there is a saying along the line "The hardest language becomes the easiest when you learn it with joy. And the easiest becomes the hardest when you have no interest in it." So definitely don't force a language on yourself.

In my experience learning Japanese, Kanji is usually the biggest headache for most. So if your like it, there's one less problem to worry about. I hated every moment spent practicing Kanji, but I like reading them. It's like having your sentence sprinkled with emojis. 😁

**Comment by matthin** [comment]
Yeah that's definitely true. I'll have to try to find some Chinese media that I actually want to consume to give me an actual goal.

Practising writing Kanji is definitely a pain, but at least in real life you rarely have to write anything out. Even in English I really don't know the last time I wrote anything out. So I think the pain of having to memorize how to write them vs the joy of reading them sort of balances out.

I pushed two commits which should hopefully fix both of the issues.

`pipenv run python3 cedict_to_sqlite.py --enable-tone-accents=true --erhua-keep-space=true` should look close to the command you run to both convert to tone accents and keep the space before each r.

It seemed like most places I looked online they all kept the r directly beside the corresponding pinyin, so that's why I had it remove the space by default.

**Comment by anhtuan23** [comment]
Props for the extra mile you took to make it an argument. However, there a bug in keeping erhua space. I've made a pull request to fix it. Please review when you have time.

**Comment by matthin** [comment]
I commented on that pull request without realizing you closed it. And GitHub didn't email me about you editing your comment so that's why I took quite a while to reply. It's weird that GitHub doesn't notify about edited comments.

That is a weird thing about Python's command line options library. I'm really not sure how to fix it other than changing it from a boolean to a string and then just manually checking for == "true" or == "false", which seems very hacky. I think it's probably okay to leave as is though and I'll just make sure to document that in the README or something.

You should send another pull request with your spelling fix.

**Comment by anhtuan23** [comment]
Okay note to self: add a new comment instead of edit when you have something more to say.

Yeah I think leaving it that way is totally ok. Just make sure to warn others so that they don't make the same mistake.

And sure, I'll make a new pull request for spelling even though it is so trivial. It's remind me about [this post on Reddi](https://www.reddit.com/r/ProgrammerHumor/comments/8f6cnb/made_my_first_big_contribution_to_open_source/)t. But seriously, proud for it to be my first pull request.

**Comment by matthin** [comment]
lol yeah I made a commit to fix a single spelling mistake in the Anki repository before. So I can now claim that I'm a developer on the Anki project.

But really spelling fixes are still good. It's not like some project maintainer is going to say no to a spelling fix.

**Comment by matthin** [comment]
You should add the email you used in your commit to GitHub so it shows up on the web interface that the commit was made by your account.

**Comment by anhtuan23** [comment]
Thanks for the tips. I use a different username and email on my personal PC from the account. Going to fix that now.
